debug:
  verbose: true

server:
  # HTTP port
  listen: 7004

  # Main control file
  index: control/index.md

  # Control pages
  page:
    title: Loopin Base Project
    nav:
      - title: Main
        page: control/index.md

      - title: Utility
        page: control/utility.md

  # This is the file that will store persistence for
  # your application.
  persist: data/persist.yaml

  # These directories will be shared under:
  #   http://localhost/files/*
  dirs:
    - control
    - preset
    - shader
    - image
    - data
